### ISSUE TITLE
Area de Midia

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/tema-brasa#15]
Inserir uma area de Midia, onde publicamos noticias sobre projetos nossos ou clientes nossos que atingiram certa popularidade por cause de seus sites.

**Comment by everaldomatias** [comment]
Obrigado pelo start @LuwkasLima, você imaginou algum lugar para isso?
Uma categoria no blog?

**Comment by LuwkasLima** [comment]
Então, a area de midia teria que ficar em uma pagina institucional ou fazer partr da Home. Pra chamar a atenção pra noticias importantes aos quais produtos e serviços Brasa influenciaram/contrubuiram.

Eu penso que logo depois de destaques....

**Comment by everaldomatias** [comment]
Conversei com o Lucas e entendi a issue, vou tocar...

**Comment by everaldomatias** [comment]
PS. nesse commit f781170d69d630d4d8cf93d7514d00824a825e7a eu adicionei o bootstrap, sorry ;)

**Comment by LuwkasLima** [comment]
@everaldomatias da pra fazer do Box um link pro artigo? Sera que nao seria mais fino que isso fosse um CPT com ACFs?

Caso nao seja possivel agora, acho que seria legal dar uma alterada na altura do Box pra ele ficar um pouco mais comprido, assim conseguimos incluir mais texto.

Abras!

**Comment by everaldomatias** [comment]
@LuwkasLima queria mesmo fazer ele mais 'fino', mas resolvi em critério de urgência e penso que uma versão melhor disso deve entrar em uma reforma geral do tema, ou mesmo um 2.0. No atual, nem ACF temos.

E sobre a localização, não sei se entendeu, mas como fiz com [shortcode] ele pode ser inserido em qualquer lugar e mais, com configurações específicas, como quantidade por exemplo.
