### ISSUE TITLE
Portifolio Cultural - Fora do Ar

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/tema-brasa#18]
Oi pessoal,

Revisando o Portifolio percebi que o Cultural está fora do ar, vejam:

![image](https://cloud.githubusercontent.com/assets/5949986/7286533/578744be-e912-11e4-93db-b82eb95c919f.png)

Tentei dar uma comparada com o Web e Design mas nao achei o problema, deve ser albo bem simples mas nao tive tempo de fuçar...

**Comment by diegorojas** [comment]
Feito Lucas! bobagem minha
