### ISSUE TITLE
Quebra de Pagina no Portfolio

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/tema-brasa#19]
Oi pessoal,

Estamos com uma quebra de pagina no portfolio, que agora possui 2 paginas por causa da quantidade de projetos que colocamos la. No entanto, onde deveria aparecer 2 projetos fica em branco:

![image](https://cloud.githubusercontent.com/assets/5949986/8195575/320be7fa-1449-11e5-9556-3ac96a681fa9.png)

**Comment by everaldomatias** [comment]
@matheusgimenez quando puder para um tempinho e coloca esse query com 18 posts, por favor.

**Comment by diegorojas** [comment]
Manos, isso aqui é mais simples hein. É só setar um numero padrão de posts multiplo de 3.

Mas atualmente está rodando no outro tema, portfolio-theme, vamos trazer tudo para esse tema-brasa antes de rever isso ai, não?

**Comment by LuwkasLima** [comment]
Nao Mano...depois vemos isso!

Deixa nesse site mesmo e so corrige pra nao ficar quebrando em 2 paginas...

Em 19 de junho de 2015 16:48, Diego Rojas <notifications@github.com>
escreveu:

> Manos, isso aqui é mais simples hein. É só setar um numero padrão de posts
> multiplo de 3.
>
> Mas atualmente está rodando no outro tema, portfolio-theme, vamos trazer
> tudo para esse tema-brasa antes de rever isso ai, não?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brasadesign/tema-brasa/issues/19#issuecomment-113652405>
> .
>



-- 
Lucas Lima
Brasa Design e Tecnologia - Veja  <http://web.brasa.art.br/>Nosso Portifólio
<http://web.brasa.art.br/>
brasa.art.br | aoseudispor@brasa.art.br | Tel.: (11)  3042-4475

**Comment by diegorojas** [comment]
Isso aqui não diz respeito ao tema-brasa e sim ao https://github.com/brasadesign/portfolio-brasa-theme Fui ver e de fato não é a configuração de exibição de posts. Não sei porque o Query está printando 16 itens. Sei que resolveremos isso trazendo para o nosso tema de vez usando o custom content types ( o que o matheus já fez) e isso estará em brasa.art.br/web

Se lá continuar o erro, reabrimos essa issue aqui, ok?
