### ISSUE TITLE
(Chat) Acesso via Celular

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/tema-brasa#5]
Pessoal, não sei se to no lugar certo, mas acessando o site da BRASA via cell eu percebi que o chat fica meio "chato" na tela, pois ocupa muito espaço e até atrapalha na visualização do video institucional.

Seria o caso de retira-lo ou modifica-lo? O que acham?

**Comment by diegorojas** [comment]
Desisitimos da ideia do chato e portanto to fechadno a issue, ok?
